version: '3'

services:
  vue:
    build: ./docker/vue
    container_name: hel_vue
    ports: 
      - 8080:8080
    volumes: 
      - .:/app
    working_dir: /app
    tty: true
    command: sh -c "cd assets && yarn install && yarn serve"

  golang:
    container_name: hel_go
    build: ./docker/golang
    ports: 
      - 8082:8082
    volumes:
      - .:/go/src/
    working_dir: /go/src/app
    tty: true
    command: fresh

  # nginx:
  #   image: nginx
  #   container_name: hel_nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./src:/var/www
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - golang
